// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBkZGzWfgpfZD7jEOASEyD7JXv1z7dwo0',
    appId: '1:463874737437:web:4cbc21d13e0c35740c0df4',
    messagingSenderId: '463874737437',
    projectId: 'cmsc186-flutter',
    authDomain: 'cmsc186-flutter.firebaseapp.com',
    storageBucket: 'cmsc186-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeJYJkfZEO-I1w4nHui90g2ir3cKVJsV4',
    appId: '1:463874737437:android:642ff9fd1ab9f41e0c0df4',
    messagingSenderId: '463874737437',
    projectId: 'cmsc186-flutter',
    storageBucket: 'cmsc186-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy1j3E2QdoCb4-AVm87Qzf_Q2XkcLNDW4',
    appId: '1:463874737437:ios:90b1254967d30e4c0c0df4',
    messagingSenderId: '463874737437',
    projectId: 'cmsc186-flutter',
    storageBucket: 'cmsc186-flutter.appspot.com',
    iosBundleId: 'com.example.internship',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy1j3E2QdoCb4-AVm87Qzf_Q2XkcLNDW4',
    appId: '1:463874737437:ios:90b1254967d30e4c0c0df4',
    messagingSenderId: '463874737437',
    projectId: 'cmsc186-flutter',
    storageBucket: 'cmsc186-flutter.appspot.com',
    iosBundleId: 'com.example.internship',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBkZGzWfgpfZD7jEOASEyD7JXv1z7dwo0',
    appId: '1:463874737437:web:2e0ec06fbdf16e680c0df4',
    messagingSenderId: '463874737437',
    projectId: 'cmsc186-flutter',
    authDomain: 'cmsc186-flutter.firebaseapp.com',
    storageBucket: 'cmsc186-flutter.appspot.com',
  );
}
